### ISSUE TITLE
Multiple Apps or Shortcuts Appear Selected at the Same Time

### ISSUE THREAD

**Issue by tommym22** [appaheadgmbh/support#68]
Summary:
In the preview section (on the left), moving the cursor over multiple apps/shortcuts in a row makes it appear as if they are all selected. This (I'm assuming visual) bug goes away when you mouse over the app again. I am not clicking anything either. This happens across all tabs (General, Switcher, Launcher, Controller) as well. 

Actions Taken to Resolve Issue:

- Quit then reopened the app
- Reinstalled the app

![Image](https://github.com/user-attachments/assets/f49f10b9-5bc7-482e-ac96-591cd4b5ce73)

**Comment by tommym22** [comment]
Update: It happens outside the settings menu as well.

**Comment by btthle** [comment]
the recent update v1.2 changed something under the hood when selecting shortcuts/apps. this blue selection background SOMETIMES does NOT appear at all now when starting pieoneer and hovering over an icon. this makes the app also not starting after clicking on it because it "thinks" it is not selected (blue)

also, the bug that @tommym22 mentioned in the screenrecording above still persists.

**Comment by martinlexow** [comment]
Thanks for your bug report—could you please let me know which macOS version you’re using the app on?

**Comment by tommym22** [comment]
Hello, thank you for getting back to me! I'm running macOS Sequoia 15.3 (24D60)

**Comment by btthle** [comment]
@martinlexow hey martin, I am on the most recent macOS Sonoma version 14.7.3

**Comment by martinlexow** [comment]
Thanks for your feedback—I originally thought it was due to macOS 14 (it seems to occur more frequently there), but unfortunately, it doesn’t seem to be limited to that. I don’t know the cause yet, but I’m looking into it—I’d appreciate any hints if you come up with anything!

**Comment by btthle** [comment]
@martinlexow I've added a short screen recording showing the multiple apps selection bug mentioned above and a new selection issue, where an app is not selected at all once hovering over it (in the video im clicking on the app icon but it did not switch to it, since it misses the blue selection background)

If it helps, I used version 1.1 before and did not encounter this issue if i remember correctly. It only started to happen after your recent update to v1.2

Both issues seem to be related to the highlighting sensitivity, it either triggers not at all after swiping over an icon or it starts "counting" all icons one by one

it should loose focus to the past icons and only select the one with the mouse pointer on it obviously.

Again, I'm on macos 14.7.3 but the issue seems OS independent

![Image](https://github.com/user-attachments/assets/94167ccd-2681-43c5-9958-f33d6bbbdfd5)

**Comment by martinlexow** [comment]
With the newly released Version 1.3, this behavior should hopefully be improved. Could you please take another look and give me feedback?

**Comment by btthle** [comment]
@martinlexow version 1.3 fixed the multiple apps selection bug as seen in the recording below.

but sometimes the blue selection does not appear (like seen in my previous post already).

I observed a different behaviour between version 1.2 and 1.3:
in version 1.2 shortcuts sometimes had no blue selection mark when pointing over them and when clicking on them, nothing happened.
in version 1.3 i can click on apps even without the blue background and it switches to them.

in summary, v1.3 fixed the multiple app selection BUT the blue selection mark still sometimes lags behind and does not appear at all. 

Debugging tip: disable the blue selection mark in v1.3 completely and you might still be able to switch apps without it as it is just a visual guidance. 

![Image](https://github.com/user-attachments/assets/6997f7c4-afd4-4391-af01-99336b54a4e2)

**Comment by tommym22** [comment]
> With the newly released Version 1.3, this behavior should hopefully be improved. Could you please take another look and give me feedback?

Looks like this issue has been resolved! There's still the weird bug of the menu appearing and getting blocked by the apple dropdown, but I can make another thread for that if need be.

**Comment by martinlexow** [comment]
@bttfck Yes, the issue only affects the background color of the selected menu item—mouse hover gestures (the app icon always scales appropriately) and clicks work reliably. I haven’t figured out the cause with the background color yet, but I’m continuing to tinker with it.

@tommym22 Could you give me more details on what the second issue is supposed to be? Which menu appears, in what circumstances, and what is it blocking? Sorry, I couldn’t follow!

**Comment by martinlexow** [comment]
There haven’t been any new bug reports on this issue in the meantime—so I’d assume the problem is resolved?

**Comment by btthle** [comment]
@martinlexow yes, 'Multiple Apps or Shortcuts Appear Selected at the Same Time' has been fixed.

but:
> Yes, the issue only affects the background color of the selected menu item—mouse hover gestures (the app icon always scales appropriately) and clicks work reliably. I haven’t figured out the cause with the background color yet, but I’m continuing to tinker with it.

-> this still happens sometimes. mostly after starting the app switcher. the launcher/controller rarely has this problem. 
i think it might be related to the number of icons shown. since the app switcher in my case has more than 8 applications open, each tile is relatively small so the trigger area (that also triggers the blue background tinting) might be overrun when quickly pointing over an icon. 

while with the controller i use only 2 shortcuts for chrome for example and the selection and background tinting pretty much never lags behind/fails

its just a visual glitch but does not break the function. pieoneer v1.5

**Comment by martinlexow** [comment]
Several months have passed, and apart from a few isolated cases, the issue now appears to be resolved. I’d therefore like to close this ticket for the time being—unless a new lead emerges that could explain why a small number of users are still experiencing this bug 🪲
